#!/usr/bin/python
import sys
import select


for i in sys.argv[1:]:
    for j in i.split():
        print "{0:b}".format(int(j))

if not sys.stdin.isatty():
    for i in sys.stdin:
        for j in i.split():
            print "{0:b}".format(int(j))
