#!/usr/bin/python
import sys
import select


for i in sys.argv[1:]:
    for j in i.split():
        print int(j,16)

if not sys.stdin.isatty():
    for i in sys.stdin:
        for j in i.split():
            print int(j,16)
